<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SoundMeeter.Models</RootNamespace>
    <AssemblyName>SoundMeeter.Update.UseCases</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SoundMeeter.Update.Contract\SoundMeeter.Update.Contract.csproj" />
    <ProjectReference Include="..\SoundMeeter.Update.Entities\SoundMeeter.Update.Entities.csproj" />
    <ProjectReference Include="..\..\SoundMeeter.Infrastructure\SoundMeeter.Infrastructure.Logger\SoundMeeter.Infrastructure.Logger.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SoundMeeter.Update.Tests" />
    <InternalsVisibleTo Include="SoundMeeter.Core" />
    <InternalsVisibleTo Include="SoundMeeter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SoundMeeter.Core\SoundMeeter.Core.Contract\SoundMeeter.Core.Contract.csproj" />
  </ItemGroup>
</Project>

